
export const chicagoDogNamesList = [
    "Sarge",
    "Tank",
    "Buster",
    "Sammy",
    "Remy",
    "Banzo",
    "Hannley",
    "Scout",
    "Dante",
    "Ginger",
    "Alexis"
]

export const fertileCrescentNamesList = [
    "Eshnunna",
    "Diniktum",
    "Tutub",
    "Der",
    "Sippar",
    "Sippar-Amnanum",
    "Kutha",
    "Jemdet Nasr",
    "Kish ",
    "Babylon",
    "Borsippa",
    "Mashkan-shapir",
    "Dilbat",
    "Nippur",
    "Marad",
    "Adab",
    "Isin",
    "Kisurra",
    "Shuruppak",
    "Bad-tibira",
    "Zabala",
    "Umma",
    "Girsu",
    "Lagash",
    "Tell Uqair",
    "Uruk",
    "Larsa",
    "Tell Khaiber",
    "Ur",
    "Kuara",
    "Eridu",
    "Tell al-'Ubaid",
    "Akshak",
    "Akkad",
    "Sanliurfa",
    "Shanidar",
    "Urkesh",
    "Tell Leilan",
    "Tell Arbid",
    "Harran",
    "Chagar Bazar",
    "Mardaman",
    "Bassetki",
    "Tell Barri",
    "Tell el Fakhariya",
    "Hadatu",
    "Carchemish",
    "Til Barsip",
    "Tell Chuera",
    "Mumbaqat",
    "Al-Rawda",
    "Tell Beydar",
    "Nagar, Syria",
    "Telul eth-Thalathat",
    "Tepe Gawra",
    "Tell Arpachiyah",
    "Shibaniba",
    "Tarbisu",
    "Nineveh",
    "Tell al-Rimah",
    "Hamoukar",
    "Dur-Sharrukin",
    "Tell Shemshara",
    "Erbil",
    "Tell Taya",
    "Hassuna",
    "Balawat",
    "Sweyhat",
    "Nimrud",
    "Emar",
    "Jarmo",
    "Arrapha",
    "Kar-Tukulti-Ninurta",
    "Assur",
    "Ekallatum",
    "Nuzi",
    "Tell al-Fakhar",
    "Terqa",
    "Dura-Europos",
    "Mari, Syria",
    "Haradum",
    "Tell es Sawwan",
    "Tell Ishchali",
    "Tell Agrab",
    "Dur-Kurigalzu",
    "Shaduppum",
    "Seleucia",
    "Ctesiphon",
    "Halabiye",
    "Hatra",
    "Ecbatana",
    "Takht-e SoleymÄn",
    "Behistun",
    "Godin Tepe",
    "Rey",
    "Chogha Mish",
    "Tappeh Sialk",
    "Susa",
    "Haft Tepe",
    "Chogha Zanbil",
    "Shahr-i Sokhta",
    "Pasargadae",
    "Naqsh-e Rustam",
    "Estakhr",
    "Persepolis",
    "Tall-i Bakun",
    "Anshan",
    "Konar Sandal",
    "Tepe Yahya",
    "Teppe Hasanlu",
    "Bam",
    "Sarvestan",
    "Hecatompylos",
    "Khorramabad",
    "Kermanshah",
    "Nimvar",
    "Isfahan",
    "Rabat Tepe",
    "Temukan",
    "Darab",
    "Hafshejan",
    "Tabriz",
    "Kangavar",
    "Shahdad",
    "Marlik",
    "Chogha Bonut",
    "Ganj Dareh",
    "Ali Kosh",
    "Geoy Tepe",
    "BÄbÄ JÄn Tepe",
    "Shah Tepe",
    "Hajji Firuz Tepe",
    "Kul Tepe Jolfa",
    "Shir Ashian Tepe",
    "Tureng Tepe",
    "Yarim Tepe ",
    "Gorgan",
    "Neyriz",
    "Dahan-e Gholaman",
    "Shushtar",
    "Shiraz",
    "Urmia",
    "Nahavand",
    "Patigrabana",
    "Bushehr",
    "Bandar Abbas",
    "Semnan, Iran",
    "Amol",
    "Karaj",
    "Yasuj",
    "Mahallat",
    "Ardericca in Susiana",
    "Hashtgerd",
    "Bit-Istar",
    "Liyan",
    "Bastam ",
    "Ganzak",
    "Jiroft ",
    "Qazvin",
    "Dezful",
    "Zanjan, Iran",
    "Ardabil",
    "Tabas",
    "Ä°nandÄ±ktepe",
    "Miletus",
    "Sardis",
    "Nicaea",
    "Sapinuwa",
    "Yazilikaya",
    "Alaca Hayak",
    "MaÅŸat Hayak",
    "Alishar Hayak",
    "Hattusa",
    "Troy",
    "KÃ¼ltepe",
    "Melid",
    "Sam'al",
    "Beycesultan",
    "Karatepe",
    "Tushhan",
    "Adana",
    "Tarsus",
    "Zephyrion",
    "Mersin",
    "Sultantepe",
    "Antalya",
    "Acre",
    "Admah",
    "Adoraim",
    "Alalakh",
    "Aleppo",
    "Antipatris",
    "Tel Arad",
    "Arqa",
    "Arwad",
    "Tartus",
    "Ashdod",
    "Ashkelon",
    "Baalbek",
    "Batroun",
    "Tel Be'er Sheva",
    "Beit She'an",
    "Bet Shemesh",
    "Bethel",
    "Bethsaida",
    "Bosra",
    "Byblos",
    "Dan",
    "Damascus",
    "Deir Alla",
    "Dhiban",
    "Tel Dor",
    "Ebla",
    "Ein Gedi",
    "En Esur",
    "Enfeh",
    "Ekron",
    "Et-Tell",
    "Gath",
    "Gaza",
    "Gezer",
    "Gibeah",
    "Gomorrah",
    "Sodom",
    "Hama",
    "Tel Hazor",
    "Hebron",
    "Jawa",
    "Jericho",
    "Tell es-Sultan",
    "Enlarge",
    "Jerusalem",
    "Jezreel",
    "Tel Kabri",
    "Kadesh",
    "Kedesh",
    "Khirbet Kerak",
    "Khirbet el-Qom",
    "Khirbet Qeiyafa",
    "Sha'arayim",
    "Kir of Moab",
    "Kumidi",
    "Kamid al lawz",
    "Lachish",
    "Tel Megiddo",
    "Qatna",
    "Amman",
    "Tel Rehov",
    "Samaria ",
    "Sarepta",
    "Sharuhen",
    "HaBesor Stream",
    "Tall al-Ajjul",
    "Tel Haror",
    "Shiloh ",
    "Sidon",
    "Palmyra",
    "Tall Zira'a",
    "Tell Balata",
    "Tell el-Hesi",
    "Tell Kazel",
    "Tell Qarqur",
    "Tell Tweini",
    "Tirzah",
    "Tyre, Lebanon",
    "Ugarit",
    "Umm el-Marra",
    "Tel Yokneam",
    "Zeboim ",
    "Zemar",
    "Zoara",
    "Al Ain",
    "Al Buraimi Governorate",
    "Tawam ",
    "Awwam",
    "Hajar Am-Dhaybiyya",
    "Barran",
    "Mecca",
    "Barbar",
    "Dhamar, Yemen",
    "Al-`Ula",
    "Dalma ",
    "Dibba",
    "Dumat Al-Jandal",
    "Ed-Dur",
    "Eudaemon",
    "Failaka",
    "Gerrha",
    "Haram ",
    "Iram",
    "Julfar",
    "Jubail",
    "Khor Rori",
    "Kaminahu",
    "Lihyan",
    "Mada'in Saleh",
    "Ma'rib",
    "Muweilah",
    "Nashan",
    "Nashaq",
    "Petra",
    "Qarnawu",
    "Qaryat al-Faw",
    "Qal'at al-Bahrain",
    "Sirwah",
    "Shabwa",
    "Shimal",
    "Tayma",
    "Tell Abraq",
    "Thaj",
    "Tarout",
    "Timna",
    "Umm al-Nar",
    "Medina",
    "Zafar",
    "Jebel Barkal",
    "Napata",
    "Meroa",
    "Axum",
    "Adulis",
    "Keskese",
    "Matara",
    "Qohaito",
    "Sembel",
    "Yeha"
]

export const chinaNamesList = [
    "李 (Lǐ)",
    "王(Wáng)",
    "张(Zhāng)",
    "刘(Liú)",
    "陈(Chén)",
    "杨(Yáng)",
    "赵(Zhào)",
    "黄(Huáng)",
    "周(Zhōu)",
    "吴(Wú)",
    "徐(xú)",
    "孙 (sūn)",
    "胡(hú)",
    "朱(zhū)",
    "高(gāo)",
    "林(lín)",
    "何(hé)",
    "郭(guō)",
    "马(mǎ)",
    "罗(luó)",
    "梁(liáng)",
    "宋(sòng)",
    "郑(zhèng)",
    "谢(xiè)",
    "韩(hán)",
    "唐(táng)",
    "冯(féng)",
    "于(yú)",
    "董(dǒng)",
    "萧(xiāo)",
    "程(chéng)",
    "曹(cáo)",
    "袁(yuán)",
    "邓(dèng)",
    "许(xǔ)",
    "傅(fù)",
    "沈(shěn)",
    "曾(zēng)",
    "彭(péng)",
    "吕(lǚ)",
    "苏(sū)",
    "卢(lú)",
    "蒋(jiǎng)",
    "蔡(cài)",
    "贾(jiǎ)",
    "丁(dīng)",
    "魏(wèi)",
    "薛(xuē)",
    "叶(yè)",
    "阎(yán)",
    "余(yú)",
    "潘(pān)",
    "杜(dù)",
    "戴(dài)",
    "夏(xià)",
    "钟(zhōng)",
    "汪(wāng)",
    "田(tián)",
    "任(rèn)",
    "姜(jiāng)",
    "范(fàn)",
    "方(fāng)",
    "石(shí)",
    "姚(yáo)",
    "谭(tán)",
    "廖(liào)",
    "邹(zōu)",
    "熊(xióng)",
    "金(jīn)",
    "陆(lù)",
    "郝(hǎo)",
    "孔(kǒng)",
    "白(bái)",
    "崔(cuī)",
    "康(kāng)",
    "毛(máo)",
    "邱(qiū)",
    "秦(qín)",
    "江(jiāng)",
    "史(shǐ)",
    "顾(gù)",
    "侯(hóu)",
    "邵(shào)",
    "孟(mèng)",
    "龙(lóng)",
    "万(wàn)",
    "段(duàn)",
    "漕(cáo)",
    "钱(qián)",
    "汤(tāng)",
    "尹(yǐn)",
    "黎(lí)",
    "易(yì)",
    "常(cháng)",
    "武(wǔ)",
    "乔(qiáo)",
    "贺(hè)",
    "赖(lài)",
    "龚(gōng)",
    "文(wén)"
]