import { euphrates, tigris, jordan } from '../region/river';

import { Region } from '../region/region';

import { dry, ocean, temperate } from '../region/climate';

import { Polity } from '../polity/polity';
import { SavedMap } from './SavedMap';


const fertileCrescentRegions = [
    new Region("A1", dry, new Polity()),
    new Region("B1", dry, new Polity()),
    new Region("C1", dry, new Polity()),
    new Region("D1", dry, new Polity()),
    new Region("E1", dry, new Polity()),
    new Region("F1", dry, new Polity()),
    new Region("G1", dry, new Polity()),
    new Region("H1", dry, new Polity()),
    new Region("I1", dry, new Polity()),
    new Region("J1", dry, new Polity()),
    new Region("K1", dry, new Polity()),
    new Region("L1", dry, new Polity()),
    new Region("A2", ocean, new Polity()),
    new Region("B2", temperate, new Polity()),
    new Region("C2", temperate, new Polity()),
    new Region("D2", temperate, new Polity()),
    new Region("E2", temperate, new Polity()),
    new Region("F2", temperate, new Polity()),
    new Region("G2", temperate, new Polity()),
    new Region("H2", temperate, new Polity()),
    new Region("I2", dry, new Polity()),
    new Region("J2", dry, new Polity()),
    new Region("K2", dry, new Polity()),
    new Region("L2", dry, new Polity()),
    new Region("A3", ocean, new Polity()),
    new Region("B3", temperate, new Polity()),
    new Region("C3", temperate, new Polity()),
    new Region("D3", temperate, new Polity()),
    new Region("E3", temperate, new Polity()),
    new Region("F3", temperate, new Polity()),
    new Region("G3", temperate, new Polity()),
    new Region("H3", temperate, new Polity()),
    new Region("I3", temperate, new Polity()),
    new Region("J3", dry, new Polity()),
    new Region("K3", dry, new Polity()),
    new Region("L3", dry, new Polity()),
    new Region("A4", ocean, new Polity()),
    new Region("B4", temperate, new Polity()),
    new Region("C4", temperate, new Polity()),
    new Region("D4", temperate, new Polity()),
    new Region("E4", temperate, new Polity()),
    new Region("F4", temperate, new Polity()),
    new Region("G4", temperate, new Polity()),
    new Region("H4", temperate, new Polity()),
    new Region("I4", temperate, new Polity()),
    new Region("J4", temperate, new Polity()),
    new Region("K4", dry, new Polity()),
    new Region("L4", dry, new Polity()),
    new Region("A5", ocean, new Polity()),
    new Region("B5", temperate, new Polity()),
    new Region("C5", temperate, new Polity()),
    new Region("D5", dry, new Polity()),
    new Region("E5", temperate, new Polity()),
    new Region("F5", temperate, new Polity()),
    new Region("G5", temperate, new Polity()),
    new Region("H5", temperate, new Polity()),
    new Region("I5", temperate, new Polity()),
    new Region("J5", temperate, new Polity()),
    new Region("K5", dry, new Polity()),
    new Region("L5", dry, new Polity()),
    new Region("A6", ocean, new Polity()),
    new Region("B6", temperate, new Polity()),
    new Region("C6", temperate, new Polity()),
    new Region("D6", dry, new Polity()),
    new Region("E6", dry, new Polity()),
    new Region("F6", temperate, new Polity()),
    new Region("G6", temperate, new Polity()),
    new Region("H6", temperate, new Polity()),
    new Region("I6", temperate, new Polity()),
    new Region("J6", temperate, new Polity()),
    new Region("K6", dry, new Polity()),
    new Region("L6", dry, new Polity()),
    new Region("A7", ocean, new Polity()),
    new Region("B7", temperate, new Polity()),
    new Region("C7", temperate, new Polity()),
    new Region("D7", dry, new Polity()),
    new Region("E7", dry, new Polity()),
    new Region("F7", dry, new Polity()),
    new Region("G7", temperate, new Polity()),
    new Region("H7", temperate, new Polity()),
    new Region("I7", temperate, new Polity()),
    new Region("J7", temperate, new Polity()),
    new Region("K7", temperate, new Polity()),
    new Region("L7", dry, new Polity()),
    new Region("A8", ocean, new Polity()),
    new Region("B8", temperate, new Polity()),
    new Region("C8", temperate, new Polity()),
    new Region("D8", dry, new Polity()),
    new Region("E8", dry, new Polity()),
    new Region("F8", dry, new Polity()),
    new Region("G8", dry, new Polity()),
    new Region("H8", temperate, new Polity()),
    new Region("I8", temperate, new Polity()),
    new Region("J8", temperate, new Polity()),
    new Region("K8", temperate, new Polity()),
    new Region("L8", temperate, new Polity()),
    new Region("A9", ocean, new Polity()),
    new Region("B9", temperate, new Polity()),
    new Region("C9", ocean, new Polity()),
    new Region("D9", dry, new Polity()),
    new Region("E9", dry, new Polity()),
    new Region("F9", dry, new Polity()),
    new Region("G9", dry, new Polity()),
    new Region("H9", temperate, new Polity()),
    new Region("I9", temperate, new Polity()),
    new Region("J9", temperate, new Polity()),
    new Region("K9", temperate, new Polity()),
    new Region("L9", temperate, new Polity()),
    new Region("A10", temperate, new Polity()),
    new Region("B10", temperate, new Polity()),
    new Region("C10", dry, new Polity()),
    new Region("D10", dry, new Polity()),
    new Region("E10", dry, new Polity()),
    new Region("F10", dry, new Polity()),
    new Region("G10", dry, new Polity()),
    new Region("H10", dry, new Polity()),
    new Region("I10", temperate, new Polity()),
    new Region("J10", temperate, new Polity()),
    new Region("K10", ocean, new Polity()),
    new Region("L10", ocean, new Polity()),
    new Region("A11", dry, new Polity()),
    new Region("B11", dry, new Polity()),
    new Region("C11", dry, new Polity()),
    new Region("D11", dry, new Polity()),
    new Region("E11", dry, new Polity()),
    new Region("F11", dry, new Polity()),
    new Region("G11", dry, new Polity()),
    new Region("H11", dry, new Polity()),
    new Region("I11", dry, new Polity()),
    new Region("J11", dry, new Polity()),
    new Region("K11", dry, new Polity()),
    new Region("L11", ocean, new Polity()),
    new Region("A12", dry, new Polity()),
    new Region("B12", ocean, new Polity()),
    new Region("C12", dry, new Polity()),
    new Region("D12", dry, new Polity()),
    new Region("E12", dry, new Polity()),
    new Region("F12", dry, new Polity()),
    new Region("G12", dry, new Polity()),
    new Region("H12", dry, new Polity()),
    new Region("I12", dry, new Polity()),
    new Region("J12", dry, new Polity()),
    new Region("K12", dry, new Polity()),
    new Region("L12", dry, new Polity()),
];

const fertileCrescentRivers = [
    euphrates,
    tigris,
    jordan
]

export const fertileCrescent = new SavedMap(fertileCrescentRegions,fertileCrescentRivers);