import { euphrates, tigris, jordan } from '../region/river';

import { Region } from '../region/region';

import { dry, ocean, temperate, continental } from '../region/climate';

import { Polity } from '../polity/polity';
import { SavedMap } from './SavedMap';


const regions = [
    new Region("A1", ocean, new Polity()),
    new Region("B1", ocean, new Polity()),
    new Region("C1", ocean, new Polity()),
    new Region("D1", ocean, new Polity()),
    new Region("E1", ocean, new Polity()),
    new Region("F1", ocean, new Polity()),
    new Region("G1", ocean, new Polity()),
    new Region("H1", ocean, new Polity()),
    new Region("I1", ocean, new Polity()),
    new Region("J1", ocean, new Polity()),
    new Region("K1", ocean, new Polity()),
    new Region("L1", ocean, new Polity()),
    new Region("A2", ocean, new Polity()),
    new Region("B2", ocean, new Polity()),
    new Region("C2", ocean, new Polity()),
    new Region("D2", ocean, new Polity()),
    new Region("E2", ocean, new Polity()),
    new Region("F2", ocean, new Polity()),
    new Region("G2", ocean, new Polity()),
    new Region("H2", ocean, new Polity()),
    new Region("I2", ocean, new Polity()),
    new Region("J2", ocean, new Polity()),
    new Region("K2", ocean, new Polity()),
    new Region("L2", ocean, new Polity()),
    new Region("A3", ocean, new Polity()),
    new Region("B3", ocean, new Polity()),
    new Region("C3", ocean, new Polity()),
    new Region("D3", ocean, new Polity()),
    new Region("E3", ocean, new Polity()),
    new Region("F3", ocean, new Polity()),
    new Region("G3", ocean, new Polity()),
    new Region("H3", ocean, new Polity()),
    new Region("I3", ocean, new Polity()),
    new Region("J3", ocean, new Polity()),
    new Region("K3", ocean, new Polity()),
    new Region("L3", ocean, new Polity()),
    new Region("A4", ocean, new Polity()),
    new Region("B4", ocean, new Polity()),
    new Region("C4", ocean, new Polity()),
    new Region("D4", ocean, new Polity()),
    new Region("E4", ocean, new Polity()),
    new Region("F4", ocean, new Polity()),
    new Region("G4", ocean, new Polity()),
    new Region("H4", ocean, new Polity()),
    new Region("I4", ocean, new Polity()),
    new Region("J4", ocean, new Polity()),
    new Region("K4", ocean, new Polity()),
    new Region("L4", ocean, new Polity()),
    new Region("A5", ocean, new Polity()),
    new Region("B5", ocean, new Polity()),
    new Region("C5", ocean, new Polity()),
    new Region("D5", ocean, new Polity()),
    new Region("E5", ocean, new Polity()),
    new Region("F5", ocean, new Polity()),
    new Region("G5", ocean, new Polity()),
    new Region("H5", ocean, new Polity()),
    new Region("I5", ocean, new Polity()),
    new Region("J5", ocean, new Polity()),
    new Region("K5", ocean, new Polity()),
    new Region("L5", ocean, new Polity()),
    new Region("A6", ocean, new Polity()),
    new Region("B6", ocean, new Polity()),
    new Region("C6", ocean, new Polity()),
    new Region("D6", ocean, new Polity()),
    new Region("E6", ocean, new Polity()),
    new Region("F6", temperate, new Polity()),
    new Region("G6", temperate, new Polity()),
    new Region("H6", ocean, new Polity()),
    new Region("I6", ocean, new Polity()),
    new Region("J6", ocean, new Polity()),
    new Region("K6", ocean, new Polity()),
    new Region("L6", ocean, new Polity()),
    new Region("A7", ocean, new Polity()),
    new Region("B7", ocean, new Polity()),
    new Region("C7", ocean, new Polity()),
    new Region("D7", ocean, new Polity()),
    new Region("E7", ocean, new Polity()),
    new Region("F7", ocean, new Polity()),
    new Region("G7", ocean, new Polity()),
    new Region("H7", ocean, new Polity()),
    new Region("I7", ocean, new Polity()),
    new Region("J7", ocean, new Polity()),
    new Region("K7", ocean, new Polity()),
    new Region("L7", ocean, new Polity()),
    new Region("A8", ocean, new Polity()),
    new Region("B8", ocean, new Polity()),
    new Region("C8", ocean, new Polity()),
    new Region("D8", ocean, new Polity()),
    new Region("E8", ocean, new Polity()),
    new Region("F8", ocean, new Polity()),
    new Region("G8", ocean, new Polity()),
    new Region("H8", ocean, new Polity()),
    new Region("I8", ocean, new Polity()),
    new Region("J8", ocean, new Polity()),
    new Region("K8", ocean, new Polity()),
    new Region("L8", ocean, new Polity()),
    new Region("A9", ocean, new Polity()),
    new Region("B9", ocean, new Polity()),
    new Region("C9", ocean, new Polity()),
    new Region("D9", ocean, new Polity()),
    new Region("E9", ocean, new Polity()),
    new Region("F9", ocean, new Polity()),
    new Region("G9", ocean, new Polity()),
    new Region("H9", ocean, new Polity()),
    new Region("I9", ocean, new Polity()),
    new Region("J9", ocean, new Polity()),
    new Region("K9", ocean, new Polity()),
    new Region("L9", ocean, new Polity()),
    new Region("A10", ocean, new Polity()),
    new Region("B10", ocean, new Polity()),
    new Region("C10", ocean, new Polity()),
    new Region("D10", ocean, new Polity()),
    new Region("E10", ocean, new Polity()),
    new Region("F10", ocean, new Polity()),
    new Region("G10", ocean, new Polity()),
    new Region("H10", ocean, new Polity()),
    new Region("I10", ocean, new Polity()),
    new Region("J10", ocean, new Polity()),
    new Region("K10", ocean, new Polity()),
    new Region("L10", ocean, new Polity()),
    new Region("A11", ocean, new Polity()),
    new Region("B11", ocean, new Polity()),
    new Region("C11", ocean, new Polity()),
    new Region("D11", ocean, new Polity()),
    new Region("E11", ocean, new Polity()),
    new Region("F11", ocean, new Polity()),
    new Region("G11", ocean, new Polity()),
    new Region("H11", ocean, new Polity()),
    new Region("I11", ocean, new Polity()),
    new Region("J11", ocean, new Polity()),
    new Region("K11", ocean, new Polity()),
    new Region("L11", ocean, new Polity()),
    new Region("A12", ocean, new Polity()),
    new Region("B12", ocean, new Polity()),
    new Region("C12", ocean, new Polity()),
    new Region("D12", ocean, new Polity()),
    new Region("E12", ocean, new Polity()),
    new Region("F12", ocean, new Polity()),
    new Region("G12", ocean, new Polity()),
    new Region("H12", ocean, new Polity()),
    new Region("I12", ocean, new Polity()),
    new Region("J12", ocean, new Polity()),
    new Region("K12", ocean, new Polity()),
    new Region("L12", ocean, new Polity()),
];

const rivers = [

]

export const testMap = new SavedMap(regions,rivers);